attention_ntk_model_args:
  smoothing: 0.01 
  test_size: 0.1
  SEED: 42
  learning_rate: 0.01
  add_noise: True
  batch_size: 512
  tau: 0.00001
  activation: "softmax"
  H: 100
  sigma: 0.01
  momentum: 0.9
  grad_norm_threshold: 0
  patience: 20
  n_splits: 9
  preprocess_mode: "rumnet"
  max_epochs: 100
  mixed_precision: False
  half: False   

SEED: 42



swiss_metro_rf_args:
  kernel_type: "gaussian"
  kernel_params:
    sigma: 5
    lengthscale: 1
  Nw: 20000
  rho: 1000
  tol: 0.000000001
  eps: 0.000000001
  smoothing: 0.01 
  n_splits: 9
  theta_std: 0.001
  lambda: 0.0000000001
  patience: 15
  SEED : 42
  learning_rate: 0.01

swiss_metro_fk_args:
  kernel_type: "1.5matern"
  SEED: 42
  learning_rate: 0.01 
  lambda: 0.00005
  patience: 20
  alpha_std: 0.01 
  smoothing: 0.01
  n_splits: 9
  test_size: 0.1
  precompute_batch_size: 1500
  optimizer: "LBFGS"
  max_epochs: 100


hotel_fk_args:
  instance_id: 5
  kernel_type: "gaussian"
  learning_rate: 0.001 
  alpha_std: 0.001 
  grad_norm_threshold: 0.0001 
  lambda: 0.00001 
  reg_batch: 1024
  max_epochs: 1000


hotel_ntk_args:
  instance_id: 1
  activation: "sigmoid"
  sigma: 0.01
  beta: 0
  learning_rate: 0.01
  optimizer: "Adam"
  H: [1024]
  max_epochs: 1000
  batch_size: 1024

expedia_ntk_model_args:
  smoothing: 0 
  test_size: 0.1
  SEED: 42
  learning_rate: 0.1
  add_noise: False
  batch_size: 512
  tau: 0.00001
  activation: "softmax"
  H: 100
  sigma: 0.001
  momentum: 0.9
  grad_norm_threshold: 0
  patience: 40
  max_epochs: 100
  mixed_precision: True
  half: False
  n_splits: 9







